steps:
  # build image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/teknasyon-cloudrun:$BRANCH_NAME', '.'
    ]
# push image(s) to GCP Cloud Registry
images:
  - 'gcr.io/$PROJECT_ID/teknasyon-cloudrun:$BRANCH_NAME'


# for more info about cloud build:
# https://cloud.google.com/build/docs/concepts